name: 🚨 Emergency Database Rescue

on:
  workflow_dispatch: # لتشغيل الكود يدوياً بضغطة زر

jobs:
  rescue_data:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Transfer Data Safely
        env:
          OLD_URL: ${{ postgresql://postgres:MvqqjPDwAqRkGGLVfBUedIbceHNkcIFx@maglev.proxy.rlwy.net:53865/railway }}
          NEW_URL: ${{ postgresql://postgres:qQbijXowxWsQgXQtyjcXdLkUtJSWWyBD@gondola.proxy.rlwy.net:21389/railway }}
        run: |
          echo "🔄 جاري الاتصال بالحساب القديم وسحب الجداول..."
          
          # هذا الأمر السحري ينسخ كل شيء (الجداول، البيانات، الهيكلة) ويصبها في الحساب الجديد
          
          pg_dump --clean --if-exists --no-owner --no-privileges "$OLD_URL" | psql "$NEW_URL"
          echo "🎉 مبروك! تمت عملية الإنقاذ بنجاح. بياناتك الآن آمنة في الحساب الجديد."
